apiVersion: apps/v1
kind: Deployment
metadata:
  name: madvsa
  labels:
    app: madvsa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madvsa
  template:
    metadata:
      name: madvsa
      labels:
        app: madvsa
    spec:
      volumes:
        - name: gcp
          secret:
            secretName: madvsa-gcs-credentials

      serviceAccountName: madvsa
      restartPolicy: Always
      containers:
        - name: madvsa
          image: madjlzz/madvsa-controlplane:latest
          imagePullPolicy: Always
          args:
            - -orchestration
            - kubernetes
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /gcp/crendetials
              name: gcp
