apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: madvsa
subjects:
  - kind: ServiceAccount
    name: madvsa
    namespace: default
roleRef:
  kind: Role
  name: madvsa
  apiGroup: rbac.authorization.k8s.io
