ARG GRYPE_VERSION=0.91.0
ARG ALPINE_VERSION=3.21.3
ARG GOLANG_VERSION=1.24

FROM golang:${GOLANG_VERSION} AS builder

WORKDIR /builder

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o grypevsa cmd/grype/main.go

FROM anchore/grype:v${GRYPE_VERSION} AS grype

FROM alpine:${ALPINE_VERSION}

WORKDIR /app
ENV PATH="$PATH:/app/bin"

COPY --from=grype /grype bin/grype
COPY --from=builder /builder/grypevsa .

ENTRYPOINT ["./grypevsa"]
CMD ["--help"]